name: SonarQube Repository Analysis Pipeline

on:
  workflow_dispatch:

env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  SONAR_URL: ${{ secrets.SONAR_URL || 'http://localhost:9000' }}

jobs:
  analyze-repositories:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install SonarScanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
          unzip sonar-scanner-cli-4.8.0.2856-linux.zip
          echo "$GITHUB_WORKSPACE/sonar-scanner-4.8.0.2856-linux/bin" >> $GITHUB_PATH
      
      - name: Run analysis and tests
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_URL: ${{ secrets.SONAR_URL }}
        run: |
          python src/main.py
      
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: sonar-analysis-results
          path: sonar_analysis_results.csv