name: SonarQube Repository Analysis Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  SONAR_URL: "https://sonarcloud.io"
  SONAR_ORGANIZATION: "drumondgit"

jobs:
  analyze-repositories:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests

      - name: Install Java 17
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk
          echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV
          echo "/usr/lib/jvm/java-17-openjdk-amd64/bin" >> $GITHUB_PATH

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Clone Axios Repository
        run: |
          git clone https://github.com/axios/axios.git repos/axios
          cd repos/axios
          npm install

      - name: Build Axios project
        run: |
          cd repos/axios
          npm run build

      - name: Install SonarScanner
        run: |
          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip -o sonar-scanner.zip
          echo "${PWD}/sonar-scanner-5.0.1.3006-linux/bin" >> $GITHUB_PATH

      - name: Verify environment
        run: |
          echo "Java version:"
          java -version
          echo "Node version:"
          node --version
          echo "NPM version:"
          npm --version

      - name: Run unit tests
        run: |
          cd repos/axios
          npm run test:node

      - name: Generate coverage
        run: |
          cd repos/axios
          npm install --save-dev nyc
          npx nyc --reporter=lcov npm run test:node

      - name: Run analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_URL: "https://sonarcloud.io"
          SONAR_ORGANIZATION: "drumondgit"
        run: |
          python src/main.py

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: sonar-analysis-results
          path: sonar_analysis_results.csv